#!/usr/bin/env python3
"""
AutoGen Agent: CloudConsultant
Generated by AI Factory
Provider: Google Gemini | Model: gemini-2.5-flash

Usage:
  1. pip install pyautogen google-generativeai google-cloud-aiplatform
  2. Set your API key as an environment variable
  3. Run: python cloudconsultant_agent.py
"""
import os
import autogen

# ── LLM Configuration ─────────────────────────────────────────────────
# Replace with your own API key or set via environment variable
API_KEY = os.getenv("AGENT_API_KEY", "AIzaSyA4ABYfLM044KkfSMSCSl6pW0nI6-TEcM4")

llm_config = {
    "config_list": [{
        "model": "gemini-2.5-flash",
        "api_key": API_KEY,
        "api_type": "google",

    }],
    "cache_seed": None,  # Disable caching for fresh responses
}

# ── Agent Definition ───────────────────────────────────────────────────
assistant = autogen.AssistantAgent(
    name="CloudConsultant",
    system_message="""[Business Context: Global Tech Solutions is in the Cloud Software vertical, generating 1k_10k targeting: Small businesses needing cloud migration..]  You are an expert cloud advisor. You help small businesses move to AWS and Azure. You are fluent in both English and Hindi. Always match the user's language.""",
    llm_config=llm_config,
)

user_proxy = autogen.UserProxyAgent(
    name="customer",
    human_input_mode="ALWAYS",
    max_consecutive_auto_reply=10,
    code_execution_config=False,
)

# ── Run ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print(f"\n============================================================")
    print(f"  AI Factory Agent: CloudConsultant")
    print(f"  Model: gemini-2.5-flash via Google Gemini")
    print(f"============================================================\n")
    print("Type your messages below. Type 'exit' to quit.\n")
    user_proxy.initiate_chat(assistant, message="Hello! How can I help you today?")
