#!/usr/bin/env python3
"""
AutoGen Agent: TestBot
Generated by AI Factory
Provider: Google Gemini | Model: gemini-2.5-flash

Usage:
  1. pip install pyautogen google-generativeai google-cloud-aiplatform
  2. Set your API key as an environment variable
  3. Run: python testbot_agent.py
"""
import os
import autogen

# ── LLM Configuration ─────────────────────────────────────────────────
# Replace with your own API key or set via environment variable
API_KEY = os.getenv("AGENT_API_KEY", "AIzaSyBrXSSJQswHKEft-GEqAQDeG_W9K_1zLDE")

llm_config = {
    "config_list": [{
        "model": "gemini-2.5-flash",
        "api_key": API_KEY,
        "api_type": "google",

    }],
    "cache_seed": None,  # Disable caching for fresh responses
}

# ── Agent Definition ───────────────────────────────────────────────────
assistant = autogen.AssistantAgent(
    name="TestBot",
    system_message="""You are a helpful assistant""",
    llm_config=llm_config,
)

user_proxy = autogen.UserProxyAgent(
    name="customer",
    human_input_mode="ALWAYS",
    max_consecutive_auto_reply=10,
    code_execution_config=False,
)

# ── Run ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print(f"\n============================================================")
    print(f"  AI Factory Agent: TestBot")
    print(f"  Model: gemini-2.5-flash via Google Gemini")
    print(f"============================================================\n")
    print("Type your messages below. Type 'exit' to quit.\n")
    user_proxy.initiate_chat(assistant, message="Hello! How can I help you today?")
